### ISSUE TITLE
Typo in /app/css/style.css on 128th line

### ISSUE THREAD

**Issue by var-bin** [codeschool/WatchUsBuild-ReadingListAppWithAngularJS#5]
Hello @alyssamichelle,

I use this repository for practicing Angular.js and I've found typo in `/app/css/style.css` on `128th` line

```css
.genre-label {
  float: left;
  width: 50%;
  margin: 0;
  cursor: pointer;
  overflow: hidden;
  text-overflow:ellipsis;
  text-tranform: capitalize; /* typo */
  white-space: nowrap;
}
```
Could you fix it?
`text-tranform` replace to `text-transform`

Thanks
